### ISSUE TITLE
下载以后，在开发环境没有问题，打包一直不不成功

### ISSUE THREAD

**Issue by yixiyimeng** [gxsandzxl/vue-electron-muti-page#1]
OKAY  take it away `electron-builder`

  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
Error: Cannot find package.json in the E:\vue-electron-muti-page-master\dist\electron
    at E:\vue-electron-muti-page-master\node_modules\_app-builder-lib@20.43.0@app-builder-lib\src\packager.ts:393:11

打包的时候，报这个错误，不知道是不是缺少文件

**Comment by shenX-2021** [comment]
缺少了/dist/electron目录，当时疏忽了，明天提交一下

**Comment by shenX-2021** [comment]
问题已经解决
